Dockerfile, run.py
Fixing run.py and Dockerfile to work better in Docker for Windows.
=> Dev.docker for windows

README.md, readalongs/app.py, readalongs/cli.py, readalongs/python_version.py
Document the minimum version of Python required. Thanks @tobyatgithub!
=> doc: add note about Python version

readalongs/align.py, readalongs/audio_utils.py, test/test_audio.py
Plus some refactoring.
Fixes: #73
=> Dev.issue73: correctly handle multiple DNA segments

readalongs/text/convert_xml.py, readalongs/views.py, requirements.txt
Plus, remove indirect python requirements from `requirements.txt`
=> refactor und code back to g2p where it was moved a while ago

readalongs/text/make_package.py
This is the small fix I mentioned to fix Marc Tessier's bug. Ideally we should be extracting the audio from video formats though.
=> fix(video): force audio mimetypes for video formats

readalongs/align.py, requirements.txt
Update to 0.1.5 and the new way of accessing configuration.
=> Update soundswallower to 0.1.5

readalongs/align.py, test/sound_swallower_stub.py, test/test_force_align.py
Still working through this but it's getting better!
=> Refactor readalongs.align

readalongs/align.py, readalongs/cli.py, test/test_align_cli.py, test/test_anchors.py, test/test_force_align.py
Add the `--align-mode` switch to `readalongs align`.
=> Dev.align mode

.pylintrc, readalongs/align.py, readalongs/cli.py, test/test_make_xml_cli.py
Fixes https://github.com/ReadAlongs/Studio-Web/issues/14
=> fix: ignore whitespace on blank lines for paragraph and page breaks

.github/workflows/codeql.yml, .pre-commit-config.yaml, readalongs/align.py, readalongs/cli.py, readalongs/epub/create_epub.py, readalongs/text/make_package.py, readalongs/text/make_smil.py, readalongs/text/util.py, readalongs/views.py, readalongs/waveform2svg/audio_util.py, readalongs/waveform2svg/units2svg.py, readalongs/web_api.py, test/test_config.py, test/test_force_align.py, test/test_misc.py
Experimenting the GitHub's own code scanning for vulnerabilities and such.
=> ci: activate CodeQL code analysis

.github/workflows/pythonpublish.yml
=> ci: submit PR instead of pushing version bump

.dockerignore, Dockerfile, requirements.min.txt
Won't be a separate PR for the maximal fix.  It's now 621MB down from 1.18GB :-)
=> Maximally fix dockerfile

LICENSE, misc-utils/accuracy.py
@littell is this all Xinjian requires?
=> feat: publish the accuracy script we used in our 2022 papers

.github/workflows/tests.yml
Same optimization we did in g2p. It's a good idea!
=> ci: suppress redundant tests runs on PR and push

README.md
The ACL anthology links are much nicer to share.
=> docs: use the CL anthology link for the SIGUL paper

readalongs/text/make_package.py, readalongs/text/make_smil.py, readalongs/text/util.py, readalongs/waveform2svg/audio_util.py, readalongs/waveform2svg/units2svg.py, readalongs/web_api.py, test/test_config.py, test/test_dna_text.py, test/test_g2p_cli.py, test/test_misc.py, test/test_silence.py, test/test_tokenize_xml.py, test/test_web_api.py
Merge in some refactoring I was doing while working on something I abandoned since.
Two useful refactoring changes:
- parse XML in only one place, so we do it right consistently, make the code DRYer, and make it easier to remember how to do it right.
- `web_apy.assemble()`: use the input_string directly with a split, instead of converting it to a StringIO just to call readlines() on it.
regular validation
low
Already covered by existing tests.
high
no
=> misc refactorings

test/data/ras-dtd-1.0.readalong, test/data/ras-dtd-1.1.readalong, test/test_dtd.py
Adding test case to check backwards compatibility of version 1.1 DTD
n/a
sanity check
LOW
test case added to test_DTD
`cd test; python test_dtd.py`
HIGH
n/a
=> test: added backwards compatibility test for DTD

docs/web-app.md
Add the reference to the tour in the Editor documentation.
Merge once the tour is deployed.
high
Editor tour: https://github.com/ReadAlongs/Studio-Web/pull/321
=> docs: mention the tour in the Web Editor docs

README.md
Document that users can get conda from Miniforge3 as a free alternative.
medium
install miniforge3 and see that conda, g2p and readalongs all works.
high
no
=> docs: document Miniforge3 as a free alternative to Miniconda3

Dockerfile, README.md
Minimal changes required to make the Dockerfile work again.
Fixes #257
basic validation
low
no, but I suppose we could create a CI workflow that builds and runs the docker image. Not sure it's worth it, though, this is really an edge use case.
```
docker build . --tag=readalong-studio
docker run --rm -p 8000:8000 -it readalong-studio
```
now runs without errors or warnings.
high
no
=> fix: minimal changes to make the Dockerfile work again

pyproject.toml
quick fix for breaking changes in click.
=> build(deps): lock click<8.2.0 since it has breaking changes

pyproject.toml, requirements.txt
Bring the dependencies up to date on the readalongs Studio backend.
low
already well covered in CI
high
no
=> build(deps): bump the prod config for Heroku
