ReadAlongs/Studio

readalongs/align.py

As discussed before, we want input file errors to generate friendly error messages. The instances of LOGGER.error() could all be sent to a separate log, if we wanted, for the web-based studio.

Replace exceptions+traceback with LOGGER.error() when detecting problems with the input files.

---

readalongs/align.py
readalongs/tempfile.py
test/run.py
test/test_force_align.py
test/test_temp_file.py

Tested on Windows only so far. Please test on Mac or Linux. I don't want to merge this if it breaks things on other platforms, and currently I'm unable to run the tests on Linux due to VPN outages.
When running `python run.py dev` in `test/`, I get two failed tests and one error on Windows, which is an improvement over master, where I get 1 failure but three errors, two of which are fixed by this PR:
```
======================================================================
ERROR: test_conversions (test_context_g2p.TestG2P)
----------------------------------------------------------------------
Traceback (most recent call last):
File "c:\Users\joanise\RAS\ReadAlong-Studio\test\test_context_g2p.py", line 34, in test_conversions
converter = make_g2p(test['in_lang'], test['out_lang'])
File …
```

Dev.temp files on windows using PortableNamedTemporaryFile

---

readalongs/cli.py
readalongs/views.py
requirements.txt
test/test_align_cli.py

Fixes https://github.com/roedoejet/g2p/issues/70
`LANGS_AVAILABLE` defined in `g2p` does not list all languages, so don't use it to define `LANGS` in ReadAlongs/Studio.
Tested for readalongs align (changes in `cli.py`), but not for `views.py`, where the same list is used, and where I therefore believe the change was also needed. The unit test suite does not exercise the code in `views.py` that uses `LANGS`, namely `step()`, and I don't know how to exercise it, so that should ideally get tested before merging this PR in.
This patch is required to successfully run `readalongs align` on any Michif data, since `crg-dv` and `crg-tmd` were not found in LANGS before this patch.

Fix LANGS list in ReadAlongs align and views

---

readalongs/align.py
readalongs/cli.py
readalongs/text/util.py
test/test_force_align.py
test/test_prepare_cli.py
test/test_tokenize_cli.py

Doing a PR for this work so I can document what I did and get some feedback.
The new command `readalongs tokenize` takes as input file an XML file created by `readalongs prepare`, runs it though the internal tokenizer, and outputs the tokenized file.
As per agreement at the last RAS dev meeting:
- "-" means stdin/stdout, for both tokenize and prepare, so the commands can be used in pipes
- if the output file name is not specified, it is auto-generated from the input file name
- both commands add .xml to the file name if it doesn't already end in .xml
- an existing output file is not overwritten by default, "-f" must be specified to do so

Adding `readalongs tokenize` to CLI, and improve `readalongs prepare`

---

readalongs/cli.py
test/.coveragerc
test/data/fra-prepared.xml
test/data/fra.txt
test/test_prepare_cli.py

Turns out paragraph and page breaks processing was broken because I opened the input text file in mode "rb" instead of "r", which meant Python did not interpret newlines the way we expect it to.
Fixed the bug by changing how we open the input file in `prepare()` in `cli.py`, and added proper output validation in a test case so we catch the problem next time I break this by accident!

Fix readalongs prepare to insert paragraph and page breaks correctly

---

readalongs/text/lexicon_g2p.py

This might be a cursed commit.
For some reason that is not obvious to me, the CMU lexicon is normalized in NFKC form (why?????). That means that text that is looked up must _also_ be in NFKC form. I believe most other text flowing through the system is in NFD form? Either way, if the cmudict file _happens_ to gain non-ASCII keys — I don't know who would do such a thing 😉 — this commit will prevent it from crashing!

fix: normalize key to NFKC in lexicon

---

requirements.txt

The version specified in requirements.txt used to import `gcd` from `fractions` (it's actually in `math`), and thus, crashed on startup. networkx 2.5 includes this commit which fixes the problem: https://github.com/networkx/networkx/commit/b007158f3bfbcf77c52e4b39a81061914788ddf9#diff-21e03bb1d46583650bcad6e960f2ab8a5397395c986942b59314033e963dd3fc

deps: bump networkx to 2.5

---

Dockerfile
README.md

Werkzeug now has to be >=0.20, which is automatically picked up when pip installing Flask.
Add more hints on using docker.
Co-authored-by:  tobyatgithub <toby.fangyuan@gmail.com>

Fix dockerfile for Werkzeug and add docs

---

misc-utils/README.md
misc-utils/non-caching-server.py
misc-utils/syll_parse.py

For a while, I've been trying to figure out how to push `syll_parse.py` and `non-caching-server.py` to GitHub in a way that respects there respective original licenses yet makes them available for optional use with ReadAlongs/Studio. This is my proposed solution: a directory called `misc-utils` where each file has its own individual licensing information right in the source code, and a description of the NRC modifications. Plus a `README.md` that says what these are and what they are used for.
I want review from Eddie Antonio Santos, Fineen Davis, Aidan Pine and Pat Littell for this PR, to make sure we're all OK with the approach I'm taking here.
Deviation for our normal model is necessary because these files are derivatives of other OSS work.

feat: Misc utility scripts that are peripheral to ReadAlongs Studio

---

readalongs/align.py
readalongs/cli.py
test/sound_swallower_stub.py
test/test_align_cli.py

align that outputs no non-noise segments should also not output stack trace 
To unit test this, I had to add more calls to `align()`, which ended up calling the SoundSwallower decoder just to exercise code in `align.py` itself, so I create a stub that lets us do quick align tests when we don't care about (or can fake) SS's output.
Fixes #88

Bug fix: align -i without -l should not output stack trace

---

readalongs/align.py
readalongs/cli.py
readalongs/text/convert_xml.py
readalongs/text/util.py
readalongs/util.py
test/data/fra-prepared.xml
test/test_align_cli.py
test/test_force_align.py
test/test_g2p_cli.py
test/test_misc.py
test/test_prepare_cli.py

as agreed on Nov 1, 2021 at the RA-S dev meeting, it's much more intuitive to
specify multiple languages with -l that having a separate option. To boot,
using an attribute mean the fallback languages can also be specified on any XML
node.
@roedoejet this CLI feature touches a lot of stuff, so I'd like its own independent review. I'll fast-forward merge it into `dev.cli` once you approve it.

refactor(cli): replace --g2p-fallback option by -l with multiple languages

---

docs/README.md
docs/cli-guide.rst
readalongs/cli.py
readalongs/text/convert_xml.py

The dev.cli branch makes a lot of changes to the CLI for readalongs. This PR updates docs/ to reflect all those changes.
It's meant to be fast-forward merged into dev.cli (via the git CLI, not via GitHub) once we're happy with it.

Updates to the documentation to reflect the refactored CLI

---

readalongs/cli.py
readalongs/text/convert_xml.py
readalongs/text/make_package.py
readalongs/text/tokenize_xml.py
readalongs/util.py
readalongs/views.py
test/test_misc.py

This PR speeds up readalongs, mostly by deferring expensive imports.
While there, added some docstrings and did additional relevant refactorings.
More review fun, @roedoejet, in case you didn't already have enough... :)
This PR speeds up the help messages quite a bit by deferring expensive imports to run them only when they're needed. 
Part of the code are cleaner too, but there's also some added complexity in other parts. I think it's a worthwhile trade off, I hope you agree!

perf: optimize the CLI, mostly by deferring expensive imports

---

test/test_audio.py

It seems these errors occur fairly often - it may be more useful to the user to report the full error message.  Also in order to fix dependencies it's necessary to run pip with some extra flags to reinstall.

Better error reporting in test_audio.py

---

docs/advanced-use.rst
docs/cli-guide.rst
docs/cli-ref.rst
docs/conf.py
docs/requirements.txt

Added a call to `readalongs langs` to embed its output right into the docs, for easiest access.
Is it reasonable to add this dependency on https://pypi.org/project/sphinxcontrib-programoutput/ / https://github.com/NextThought/sphinxcontrib-programoutput ? It seems well maintained.

docs: embed the list of languages right in the doc

---

readalongs/align.py
readalongs/api.py
readalongs/cli.py
readalongs/text/make_package.py
readalongs/util.py
readalongs/views.py
test/run.py
test/test_api.py

Immediate use case: ReadAlongsDesktop can now avoid repeating code already written by readalongs.cli, by calling the wrappers in readalongs.api.
The advantage of these wrappers over calling the underlying functions in readalongs.align etc is that all the error checking logic implemented in readalongs.cli is applied. The calls are equivalent to command line calls, but without going through a system call.

Create an API for ReadAlongs/Studio from the click app.

---

.github/workflows/tests.yml
readalongs/align.py
readalongs/cli.py
readalongs/text/convert_xml.py
test/test_align_cli.py
test/test_g2p_cli.py

This bringing in a hidden feature we created for the ras-evaluation done for the ComputEL and SIGUL papers.

Dev.oo option: add hidden -oo option to control output orthography

---

readalongs/text/convert_xml.py
readalongs/text/util.py
test/data/patrickxtlan.xml
test/test_g2p_cli.py

Words can now have sub-word structure. The text go g2p is collected from
all text in the <w> element and its sub-elements.
Sub-elements can have their own lang="lang_code" attribute. Like before,
we collect all text with the same language code and g2p it together,
then concatenate the results from g2p'ing the text in different
languages.
Note, however, that the fallback-langs attribute is only allowed on the
<w> elements and its parents, not on sub-word elements.

feat: re-introduce the sub-word functionality in Studio

---

readalongs/align.py
test/test_audio.py
test/test_force_align.py

Turns out that since -loglevel was implemented, debug_aligner has the unintended side effect of turning *off* most logging.  This changes the handling of logs to be more logical.  We don't send them to /dev/null now that we can control the log level (only errors are printed by default).  With save_temps we turn most logging on and send it to a file.  With debug_aligner we dump everything to the console.
In practice INFO and DEBUG are the same thing but that might not always be the case.

feat: clean up log handling and fix debug_aligner

---

CITATION.cff
README.md

- Added a CITATION.cff with the info, which causes GitHub to display a
"Cite this repository" button in the About section.
- But for convenience and because it's normally where I would look,
also add the BibTeX info in README.md
FIXES: #116

docs: Ask users to cite our SIGUL 2022 paper

---

readalongs/align.py
readalongs/text/make_smil.py
readalongs/web_api.py
test/run.py
test/test_force_align.py
test/test_smil.py
test/test_web_api.py

Feature implementation: the `/convert_alignment` endpoint supports converting alignments to TextGrid, eaf, srt, vtt.

feat: add /convert_alignment endpoint

---

.github/workflows/tests.yml
README.md
readalongs/web_api.py

instead of the confusing PRODUCTION= you now do DEVELOPMENT=1 (or anything else truthy), and you can also explicitly specify the deployed origin URL with ORIGIN if you like for production mode (fixes #146)

Introduce better CORS environment variables

---

readalongs/log.py
readalongs/web_api.py
test/test_misc.py
test/test_web_api.py

Addresses https://github.com/ReadAlongs/Web-Component/issues/92 at least in part, in that g2p logs and everything else `/assemble` logs now goes to a `log` field in the JSON payload.
I did not capture the logs from `/langs` since that received no input and doesn't log anything anyway.
I did not (yet) capture the logs from `/convert_alignment` but I think I should do that one too.

Web API: Capture assemble logs

---

readalongs/web_api.py
test/test_web_api.py

Change back to /api/v1 endpoints for the web api. After ICLDC, if we make any breaking changes, we should *keep* v1 but then also add a new `v2 = FastAPI()` to register the new endpoints at. We can determine how long we will support old endpoints for at a later date.

refactor(webapi): change back to v1

---

readalongs/text/make_package.py
test/test_package_urls.py

Gracefully handle the situation where unpkg is slow and times out

handle unpkg timeouts

---

readalongs/web_api.py
test/test_web_api.py

500 was internal error, but aligning something like `.` as the whole text should yield a clear message to the user, not an internal error.

fix: where there are no words to align, return 422, not 500

---

.github/workflows/pythonpublish.yml

1) Replace deprecated actions/create-release by ncipollo/release-action
https://github.com/actions/create-release is deprecated so we should
stop using it. ncipollo/release-action is one of its maintained
replacements, and the one our mathieudutour/github-tag-action actions
uses in their documentation.
Linted with https://rhysd.github.io/actionlint/ but we can't really test
this without creating a new release, so we'll have to test it when it's
time to create the next release.
2) ci: replace deprecated set-output and bump github-tag-action
Refs for set-output:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
For …

ci: fix deprecation warnings for actions/create-release and set-output

---

requirements.api.txt

The idea of this commit is that studio as published on PyPI still depends on a g2p release as declared in `requirements.min.txt`, but the live system on Heroku uses the current main branch from GitHub instead.

build: force the latest g2p@main for heroku

---

readalongs/align.py

A healthy dose of silencing for mypy (because SoundSwallower's type annotations may be slightly bogus)

Update search for noise dictionary to match all SoundSwallower versions (fixes #183)

---

requirements.api.txt
requirements.min.txt

We had changed things so Heroku builds always took origin/main for g2p, but now that we're working on g2p 2.0 with breaking changes, we have to revert this change and get the latest g2p 1.1.* release instead.
Fixes #186

fix: g2p main is about to be 2.0, but we still want 1.1 on Heroku

---

readalongs/log.py
requirements.min.txt

See: https://pythonspeed.com/articles/numpy-2
When numpy 2.0.0 is actually out, we'll want to test g2p and our other projects against it before allowing it.
Also fix the bold bug with coloredlogs, long ago fixed in g2p, which prevented us from updating it.

lock numpy < 2

---

.github/workflows/matrix-tests.yml
requirements.min.txt

This makes RAS properly compatible with Python 3.11 everywhere, although installation on Windows will require a compiler until the SoundSwallower wheels are published for 3.11 (see https://github.com/ReadAlongs/SoundSwallower/issues/60)

Bump lxml to a version compatible with Python 3.11 on Windows

---

readme-heroku.md

Last summer, I documented how our Heroku deployment is controlled, but I just noticed this file, never committed, never pushed... I checked, and I believe it's still accurate.

docs: document how our builds on Heroku are controlled

---

.github/workflows/matrix-tests.yml
.github/workflows/tests.yml
readalongs/audio_utils.py
readme-heroku.md
requirements.min.txt
test/basic_test_case.py
test/run.py
test/test_force_align.py
test/test_web_api.py

Please see the individual commit messages for what's all in here.

A bunch of maintenance work for the repo

---

requirements.dev.txt

No code changes to commit, the differences between black 22 and 23 do not currently affect the code base because I committed those changes a while ago.
When we merge this, developers should reinstall black with  `pip install -r requirements.dev.txt` in their Python environments.

style: bump black to 23

---

requirements.min.txt

The authors published 0.8.1 with proper 3.12 packages.
Fixes: #202

fix: editdistance can now come from PyPI again for Py 3.12

---

.pre-commit-config.yaml
readalongs/web_api.py
requirements.min.txt

- Declare our dependency on Pydantic. We're actually super relaxed: `web_api.py` breaks with Pydantic 1.7, but works fine from 1.8.2 to 2.x, so I made it that broad. I'm going to rely on FastAPI's exclusions to block out "bad" version, I don't feel the need to duplicate that here. E.g., `fastapi==0.110.1` wants `pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4` (!!!)
- Pydantic 2 does not allow `Field(example="foo")`, only `Field(examples=["foo"])`, while Pydantic 1 is happy with either, so let's only use the latter to suppress the deprecation warning.
- And the ancient flake8 use used in `.pre-commit-config.yaml` was broken on my machine, so I bumped it to the current version.
Fixes #215

Fix pydantic issues

---

docs/cli-guide.rst
docs/cli-ref.rst
docs/index.rst
docs/requirements.txt

Add a link to the old Sphinx base documentation to point to the new location.
While I'm here, fix two syntactic errors so the latest version on https://readalong-studio.readthedocs.io/ will display correctly. (I had to fix them for the convert to .md to work correctly.)
Prepares the way for #213
Related to #223
normal
n/a
locally build and examine the docs:
```
cd docs
pip install -r requirements.txt
make html    # or: sphinx-build -M html . _build
cd _build/html
python -m http.server
```
then navigate to http://127.0.0.1:8000 and see:
then make sure the link forward to the new docs is good.
high
no
@roedoejet Once we merge this we'll need to do a final documentation push to readthedocs and make sure https://readalong-studio.readthedocs.io/en/latest/ gets updated with the …

Dev.ej/prep for mkdocs

---

readalongs/static/read-along-1.1.dtd

fixing read-along DTD version 1.1 . The XML package is adding id to meta tag, adjusted the DTD to allow meta to have id attributes 
fix DTD validation error
HIGHEST
n/a
HIGH
n/a

fix: added optional id to meta tag attributes

---

readalongs/cli.py

Fix a very minor typo in readalongs/cli.py
As mentioned above.
Low
N/A
N/A

fix: very minor typo correction in cli.py

---

requirements.min.txt

Deliberately exclude panphon 0.21 since it's not compatible with Python 3.8

fix(deps): exclude panphon 0.21 not compat with Python 3.8

---

docs/cli-guide.md
readalongs/align.py
readalongs/web_api.py

I believe these additional places need the version bumped to match the latest dtd version too, but I'd like confirmation I'm not misinterpreting anything here.

fix: more places where the current dtd 1.2 version is needed

---

requirements.api.txt

Fix a CVE in gunicorn.
Fix https://github.com/advisories/GHSA-w3h3-4rj7-4ph4
possibly high?
already covered in CI
High if CI passes.
no

fix(deps): gunicorn 23 has vulnerability fixes that seem worthwhile

---

.github/workflows/pythonpublish.yml

Nothing works today. 🙁
Can't publish studio.
Finding last minutes bugs in studio-web.
Bleh.
Here, I'm guessing the way we published to pypi is no longer supported. See #240.
This code is mimicked from g2p, but not tested. Please review carefully.
Before this can work, we'll need to add the PYPI_API_TOKEN to this repo's secrets, and we can probably remove the obsolete PyPI username and password secrets since they don't work anymore anyway.

fix: fix (or attempt to fix) the pypi publication process

---

readalongs/web_api.py

I don't know what causes this, but we got a few 5xx errors from the Heroku logs with this trace:
```
File "/app/readalongs/web_api.py", line 209, in assemble
parsed = parse_xml(
^^^^^^^^^^
File "/app/readalongs/text/util.py", line 138, in parse_xml
return etree.fromstring(
^^^^^^^^^^^^^^^^^
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 3, line 8, column 26
```
While it makes no sense we should fail to parse XML we just generated in this broader block:
```
parsed = parse_xml(
create_ras_from_text(
(request.input_text or "").splitlines(keepends=True),
text_languages=request.text_languages,
)
)
```
let's just put a try/except in there since we saw it live on Heroku.
Whatever the error in the input is, though I cannot reproduce it, should generate a 422 HTTP code.
Fix the 5xx errors we …

fix: catch exceptions due to failure to create XML from text

---

requirements.min.txt

The `pydub` dependency was unduly restrictive, I tested and we're compatible with all more recent versions too.
low
matrix test in CI will exercise this
high
no

fix(deps): relax the pydub requirement to allow the latest

---

readalongs/web_api.py
requirements.min.txt

Before fastapi 0.99, we could declare multiple examples with
examples=[{"key1": ..., "key2": ...}]
Now, examples no longer accept keys or metadata, just a list of plain examples.
Since fastapi 0.103, using openapi_examples instead restores the old key and metadata functionality.
See https://fastapi.tiangolo.com/tutorial/schema-extra-example/#using-the-openapi_examples-parameter for details.
Make the examples for `/assemble` work again on https://readalong-studio.herokuapp.com/api/v1/docs#/default/assemble_assemble_post
Currently, the proposed example is invalid:
This PR brings it back to what we used to have:
low
n/a
```
pip install uvicorn
cd readalongs/
DEVELOPMENT=1 uvicorn readalongs.web_api:web_api_app --reload
```
then navigate to …

fix: repair how multiple examples are declared in web_api

---

README.md
run-web-api.sh

Stop repeating myself when I want to run the web api, but scripting this command I always have to look up and cut-and-paste!
Simplifies launching the Web API in dev mode.
Sanity checking
low
n/a
Run `./run-web-api.sh`, or `/path/to/sandboxes/Studio/run-web-api.sh` from anywhere, and see the dev web API launched at http://127.0.0.1:8000/api/v1/docs 
high
no

feat: add run-web-api.sh to easy launch dev mode API server

---

.pre-commit-config.yaml
readalongs/text/make_package.py
test/basic_test_case.py
test/run.py
test/test_anchors.py
test/test_api.py
test/test_audio.py
test/test_dna_text.py
test/test_force_align.py
test/test_g2p_cli.py
test/test_misc.py
test/test_tokenize_xml.py
test/test_web_api.py

Reduce the amount of output we get from running test test suites.
Now, `test/run.py --quiet` (using this new option I added), you get just dots:
```
$ test/run.py --quiet
INFO - No test suite specified, defaulting to dev.
..........................................................................................................................................
----------------------------------------------------------------------
Ran 138 tests in 39.697s
OK
```
like a well-behaved test suite.
my annoyance at verbose test suite output
medium
it's only tests...
Run `test/run.py` and `test/run.py --quiet` and enjoy the (relative) silence.
high
no

Silence all test suites

---

readalongs/api.py
readalongs/text/make_package.py
readalongs/text/util.py
test/test_api.py

Add an API function to convert a sequence of tokens to an Offline HTML file.
Related to https://github.com/EveryVoiceTTS/EveryVoice/issues/439
general review and validation
EV beta
yup
The easiest is to exercise via EV: see https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/103
pretty high
yeah, we've been adding features, so a minor bump would make sense soon. It'll be required before publishing EV with a requirement on this feature.

Dev.ej/convert to offline html

---

.github/workflows/tests.yml
bin/post_compile
readalongs/align.py
readalongs/align_utils.py
readalongs/api.py
readalongs/cli.py
readalongs/web_api.py
readme-heroku.md
requirements.txt
test/test_force_align.py
test/test_make_xml_cli.py

align.py is a monster file doing too much stuff. This PR takes the alignment I/O out to align_utils.py.
The work was inspired by #170, which is non essential, but I decided to do it because it makes the code somewhat cleaner, and the Heroku image leaner.
~Not done: I'm not sure how to declare, when updating `requirements.txt` from `pyproject.toml`, to exclude soundswallower...~ (added documentation to do it on update).
Fixes #170
low
This was almost all already covered by existing tests. I just had to do minor tweaks on the heroku workflow to streamline it.
high
no

refactor align helper functions out of align.py

---

readalongs/text/make_package.py
test/test_api.py

For a process using `convert_prealigned_text_to_offline_html()` in the Studio API to create a number of different readalongs, fetching the bundles is pretty slow, and has to be done repeatedly for each readalong created. Running the EveryVoice demo on our cluster, that represented an additional 3 second delay each time I clicked the synthesize button, on top of the actual synthesis time.
The solution I adopted here is simply to save the bundle contents in a file-global variable in `make_package.py`, so we only ever try to fetch each of the two bundle files once.
Memory cost: the bundles take 600KB together, so after the first fetch I'm reserving .6MB for this cache, which is pretty trivial.
low
~code already covered~
Yes
Run the everyvoice demo with this branch of Studio …

perf: cache the bundles after we fetched them once

---

readalongs/text/convert_xml.py
readalongs/web_api.py
test/test_web_api.py

I can still generate 503 with large text via the API, so this PR enforces the time limit on the whole of assemble, not just on g2p processing.
before ICLDC
yes
requires messing with the API directly, giving it a very large payload.
high
no

fix: enforce time limit on assemble as a whole, not just g2p

---

readalongs/align_utils.py
readalongs/cli.py
readalongs/text/convert_xml.py
readalongs/text/make_package.py
readalongs/web_api.py
test/test_g2p_cli.py
test/test_web_api.py

In assemble, just list the words that could not be g2p'd, so the error message shown to the user in Studio-Web is legible.
In the CLI, add a summary list of the words that could not be g2p's in the error message.
Unreadably verbose errors shown to users in Studio-Web when some tokens cannot be g2p'd.
before ICLDC ideally
yes
In Studio:
```
./run_web_api.sh
```
In Studio-Web:
```
npx nx build web-component
npx nx serve studio-web
```
Navigate to http://localhost:4200/ and put non-g2p-able text like `54:23 1223:563 54:23` and see the nice and sweet error message like this when you click on next step:
high
Before ICLDC, I might choose to bump Studio's version to 1.2.2 with the several little patches we've done recently.

feat: summarize g2p errors in assemble and on the CLI

---

readalongs/cli.py

While improving the documentation in #267 with Marc's feedback, there are three changes to the CLI I want to make, which I think should get their own separate review:
- The most important is that I want to have `readalongs align` always generate the Offline HTML, like we do in Studio-Web, because it's the artefact that can be uploaded into the Editor.
- Second: `readalongs prepare` has been marked deprecated for more than two years, I think we can hide it from the `readalongs -h` documentation.
- Third: Marc pointed out `readalongs align` gives an error when `-l <lang>` is missing, but in S-Web we default to `und` instead. While not defaulting to `und` in the CLI (or should we?) I made `-l und` a more prominent thing, both in the help messages, and in the error message you get if you omit …

Dev.ej/cli tweaks

---

readalongs/text/make_package.py
readalongs/text/util.py
test/test_align_cli.py
test/test_api.py
test/test_package_urls.py

This work was triggered by noticing that a .html file someone just sent us was hard to analyse by hand, in terms of what versions of things were used. So I decided to add newlines so that the text part of stuff is still visible when you disable line-wrapping, and add more versioning information to the generated files. There will be a similar PR for S-Web soonish.
While I was there, I did some clean up and refactoring and added the instructions for opening the offline HTML file from Google Drive, copied from S-Web.
General validation
normal
Use the CLI to create a readalong, with `-o html`, and look at the generated `www/index.html` and `Offline-HTML/<name>.html`.
good
no

Several improvements to the HTML files created by RAS CLI
